site_name: Model Data Stack Learning 
site_description: Learning Materials
site_author: 'Vicky Guo'

theme:
  name: 'readthedocs'


copyright: 'Copyright &copy; 2022 Vicky Guo'

repo_name: 'GitHub'
docs_dir: docs/
repo_url: https://github.com/VickyGuo0907/datastack-learning
edit_uri: edit/master/docs/

# Plugins
plugins:
  - search

# Launch external urls in separate tab
extra_javascript:
  - js/links_in_new_tabs.js

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list
  
#Page tree
nav:
  - Home: index.md
  - Data Stack Concept:
    - Base Concept: concept/base-concept.md
    - Modern Data Stack: concept/modern-data-stack.md
    - Modern Data Stack V2: concept/modern-data-stack-v2.md
  - Data Workflow tools:
    - Base Concept: dataflow/base-concept.md
    - Task Orchestration Tools: dataflow/task-tools.md
  - Data Gavernance:
    - Metadata Management: datagov/metadata-tools.md
  




